server:
  port: 8092

spring:
  datasource:
    # sqlite
#    username:
#    password:
#    url: jdbc:sqlite:D:\cache\acgnmanager\books.db
#    driver-class-name: org.sqlite.JDBC
    username: root
    password: Mysql11..
    url: jdbc:mysql://localhost:3306/acgnmanager?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      max-active: 16
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from library
      filters: stat,slf4j,config
